### ISSUE TITLE
Alignment Windows for Partners of the same color identity don't have the division

### ISSUE THREAD

**Issue by Elonex777** [Lithl/challenge32#2]
Examples: 
- Tymna & Ravos
- Kydele & Thrasios

**Comment by Lithl** [comment]
This bug is caused by the logic for deciding whether the adjustment window should be using a divided display (for partners) or not. Currently, the logic assumes that if a commander has exactly the color identity that's been selected in the edit tab, then it must not be a partner. This same error would occur in identities other than enemy guilds, if such partner pairs existed.

**Comment by Lithl** [comment]
resolved by 711a6ff449c7eaba4215b08a25dff099e95c25de
