### ISSUE TITLE
Cached image adjustment values with partner commanders

### ISSUE THREAD

**Issue by Lithl** [Lithl/challenge32#55]
If you adjust an image, those adjustment values are cached, being associated with the image url. This is useful if you adjust one commander, switch commanders, then switch back: your adjustments are still there. However, if you use a partner commander, this can cause problems, since they can fit into multiple color identities.

For example, selecting Ishai as your Azorius commander (full width) would warrant different image adjustment values from using Bruse and Ishai for your Jeskai commanders (right side), which would warrant different values from using Ishai and Kydele for our Bant commanders (left side). Currently, the system will only use the most-recently set adjustment values for Ishai in all three cases.

**Comment by Elonex777** [comment]
Partner, need far more alignment values that that, let's use Ishai example:
- Alone (Azorius) ==> (0 | -3 | 1 | 0,96)
- Left Obtuse Triangle (Jeskai with kraum or ludevic) ==>(-12,9 | -0,2 | 0,97 | 0,97)
- Right Obtuse Triangle (Jeskai with akiri or bruse) ==>(7,7 | -4,2 | 0,88 | 0,88)
- Left Acute Triangle (Bant & Esper) ==>(-16,4 | 0 | 1,26 | 1,26)
- Left Petal (Not-Red with Reyhan, Not-Green, Not-Black) ==> (not done yet)
- Right Petal (Not-Red with Ikra) ==> (not done yet)

Some have more possibilities than others (like partner with the same color combination have also trapezoid), because that is based with alphabetical (first in alphabet always at left position) to avoid some possible combination, i listed every combination with the correct values, here: https://docs.google.com/spreadsheets/d/1vvj3Rz-vU6QJgqnHAGqz0Xw5FvySj0ZQwRo5XRFSbbo/edit?usp=sharing

If your current system can support all these combinations (and more for other partner commander) then you can close it again.

**Comment by Lithl** [comment]
Irrelevant to this bug. See #37 instead.
