### ISSUE TITLE
Sometime the alignment values are not saved 

### ISSUE THREAD

**Issue by Elonex777** [Lithl/challenge32#57]
And the only way to make it work is to change the selected commander for another one and change it again to the previous commander you choose.

It seems to happen when you wait "too long" to change values, to reproduce it choose a commander wait several minutes and then try to change the values and save.

For now it happened to me with orzhov, azorius, jeskai, mardu, abzan and temur.

**Comment by Lithl** [comment]
The root cause of this issue is not a matter of time, but whether the most recently set commander is the color identity of the commander being edited. When the image adjustments are confirmed, the system gets notified to update the display of the color identity for the commander that was most recently selected, rather than the color identity of the commander that was just adjusted. Obviously wrong.

**Comment by Elonex777** [comment]
I still have this issue but not exactly the same:
Add a commander, change values, save, reopen it and change the selected commander. Then when you want to change value of this second commander the save feature is not working. And if you open it again you can see that the value are set back to 0,0,1,1.
